name: 'Testnet Environment Setup'
description: 'Installs NodeJS, PNPM, dependencies and PNPM restores cache'

runs:
  # composite allows us to bundle multiple workflow steps into a single action
  using: 'composite'

  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v5
      with:
        node-version: 'lts/iron'

    - name: Install PNPM
      uses: pnpm/action-setup@v2
      with:
        run_install: false
        # we do not need to specify PNPM's version since we have the `packageManager`
        # property set in `package.json`

    - name: Get PNPM store path
      id: pnpm-cache
      shell: bash
      run: |
        echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup PNPM cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
